[global]
# グローバル設定
developmentMode = false
dataFrameSerialization = "legacy"

[server]
# サーバー設定
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = true
headless = true
runOnSave = false
allowRunOnSave = false
fileWatcherType = "auto"

[browser]
# ブラウザ設定
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
# テーマ設定
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# クライアント設定
caching = true
displayEnabled = true
showErrorDetails = true