[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
baseUrlPath = ""
allowRunOnSave = true
runOnSave = false
maxUploadSize = 1028

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "light"

[global]
developmentMode = false
suppressDeprecationWarnings = true

